/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdValidateRouteImport } from './routes/p.$projectId.validate'
import { Route as PProjectIdTrainRouteImport } from './routes/p.$projectId.train'
import { Route as PProjectIdReplayRouteImport } from './routes/p.$projectId.replay'
import { Route as PProjectIdReconstructRouteImport } from './routes/p.$projectId.reconstruct'
import { Route as PProjectIdCaptureRouteImport } from './routes/p.$projectId.capture'
import { Route as PProjectIdBuildRouteImport } from './routes/p.$projectId.build'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/p/$projectId/',
  path: '/p/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdValidateRoute = PProjectIdValidateRouteImport.update({
  id: '/p/$projectId/validate',
  path: '/p/$projectId/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdTrainRoute = PProjectIdTrainRouteImport.update({
  id: '/p/$projectId/train',
  path: '/p/$projectId/train',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdReplayRoute = PProjectIdReplayRouteImport.update({
  id: '/p/$projectId/replay',
  path: '/p/$projectId/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdReconstructRoute = PProjectIdReconstructRouteImport.update({
  id: '/p/$projectId/reconstruct',
  path: '/p/$projectId/reconstruct',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdCaptureRoute = PProjectIdCaptureRouteImport.update({
  id: '/p/$projectId/capture',
  path: '/p/$projectId/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdBuildRoute = PProjectIdBuildRouteImport.update({
  id: '/p/$projectId/build',
  path: '/p/$projectId/build',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId/build': typeof PProjectIdBuildRoute
  '/p/$projectId/capture': typeof PProjectIdCaptureRoute
  '/p/$projectId/reconstruct': typeof PProjectIdReconstructRoute
  '/p/$projectId/replay': typeof PProjectIdReplayRoute
  '/p/$projectId/train': typeof PProjectIdTrainRoute
  '/p/$projectId/validate': typeof PProjectIdValidateRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$projectId/build': typeof PProjectIdBuildRoute
  '/p/$projectId/capture': typeof PProjectIdCaptureRoute
  '/p/$projectId/reconstruct': typeof PProjectIdReconstructRoute
  '/p/$projectId/replay': typeof PProjectIdReplayRoute
  '/p/$projectId/train': typeof PProjectIdTrainRoute
  '/p/$projectId/validate': typeof PProjectIdValidateRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId/build': typeof PProjectIdBuildRoute
  '/p/$projectId/capture': typeof PProjectIdCaptureRoute
  '/p/$projectId/reconstruct': typeof PProjectIdReconstructRoute
  '/p/$projectId/replay': typeof PProjectIdReplayRoute
  '/p/$projectId/train': typeof PProjectIdTrainRoute
  '/p/$projectId/validate': typeof PProjectIdValidateRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId/build'
    | '/p/$projectId/capture'
    | '/p/$projectId/reconstruct'
    | '/p/$projectId/replay'
    | '/p/$projectId/train'
    | '/p/$projectId/validate'
    | '/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$projectId/build'
    | '/p/$projectId/capture'
    | '/p/$projectId/reconstruct'
    | '/p/$projectId/replay'
    | '/p/$projectId/train'
    | '/p/$projectId/validate'
    | '/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId/build'
    | '/p/$projectId/capture'
    | '/p/$projectId/reconstruct'
    | '/p/$projectId/replay'
    | '/p/$projectId/train'
    | '/p/$projectId/validate'
    | '/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdBuildRoute: typeof PProjectIdBuildRoute
  PProjectIdCaptureRoute: typeof PProjectIdCaptureRoute
  PProjectIdReconstructRoute: typeof PProjectIdReconstructRoute
  PProjectIdReplayRoute: typeof PProjectIdReplayRoute
  PProjectIdTrainRoute: typeof PProjectIdTrainRoute
  PProjectIdValidateRoute: typeof PProjectIdValidateRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/validate': {
      id: '/p/$projectId/validate'
      path: '/p/$projectId/validate'
      fullPath: '/p/$projectId/validate'
      preLoaderRoute: typeof PProjectIdValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/train': {
      id: '/p/$projectId/train'
      path: '/p/$projectId/train'
      fullPath: '/p/$projectId/train'
      preLoaderRoute: typeof PProjectIdTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/replay': {
      id: '/p/$projectId/replay'
      path: '/p/$projectId/replay'
      fullPath: '/p/$projectId/replay'
      preLoaderRoute: typeof PProjectIdReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/reconstruct': {
      id: '/p/$projectId/reconstruct'
      path: '/p/$projectId/reconstruct'
      fullPath: '/p/$projectId/reconstruct'
      preLoaderRoute: typeof PProjectIdReconstructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/capture': {
      id: '/p/$projectId/capture'
      path: '/p/$projectId/capture'
      fullPath: '/p/$projectId/capture'
      preLoaderRoute: typeof PProjectIdCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/build': {
      id: '/p/$projectId/build'
      path: '/p/$projectId/build'
      fullPath: '/p/$projectId/build'
      preLoaderRoute: typeof PProjectIdBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdBuildRoute: PProjectIdBuildRoute,
  PProjectIdCaptureRoute: PProjectIdCaptureRoute,
  PProjectIdReconstructRoute: PProjectIdReconstructRoute,
  PProjectIdReplayRoute: PProjectIdReplayRoute,
  PProjectIdTrainRoute: PProjectIdTrainRoute,
  PProjectIdValidateRoute: PProjectIdValidateRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
